project:
  type: website
  output-dir: docs

website:
  title: "Aida Aquino's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
        href: portfolio-planning-master/portfolio-planning.qmd
        text: "Portfolio Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

